import logging
import os
import pathlib

from dotenv import load_dotenv

# Load .env from this file's directory so it works regardless of cwd.
# override=True ensures the .env wins over any stale shell var.
_dotenv_path = pathlib.Path(__file__).parent / ".env"
_loaded = load_dotenv(_dotenv_path, override=True)
logging.basicConfig(level=logging.INFO)
logging.info(
    ".env at %s -> %s | ANTHROPIC_API_KEY present: %s",
    _dotenv_path, _loaded, bool(os.getenv("ANTHROPIC_API_KEY")),
)

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import create_tables
from routers import modules, scenarios, leaderboard, matching, triage, radio, violations, adventure, volunteers, reminders

logging.basicConfig(level=logging.INFO)

app = FastAPI(
    title="Volunteer Training API",
    description="Backend for the interactive volunteer training game. Domain knowledge lives in YAML; exercises are generated by Claude.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "http://localhost:3000").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(modules.router, tags=["modules"])
app.include_router(scenarios.router, tags=["games"])
app.include_router(matching.router, tags=["games"])
app.include_router(triage.router, tags=["games"])
app.include_router(radio.router, tags=["games"])
app.include_router(violations.router, tags=["games"])
app.include_router(adventure.router, tags=["games"])
app.include_router(leaderboard.router, tags=["leaderboard"])
app.include_router(volunteers.router)
app.include_router(reminders.router)


@app.on_event("startup")
def startup():
    create_tables()
    # Eagerly validate all YAML files so bad files surface at boot, not mid-game
    from knowledge import load_all_modules
    loaded = load_all_modules()
    logging.info("Loaded %d module(s): %s", len(loaded), list(loaded.keys()))


@app.get("/health")
def health():
    return {"status": "ok"}
