import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import create_tables
from routers import modules, scenarios, leaderboard

load_dotenv()
logging.basicConfig(level=logging.INFO)

app = FastAPI(
    title="Volunteer Training API",
    description="Backend for the interactive volunteer training game. Domain knowledge lives in YAML; exercises are generated by Claude.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "http://localhost:3000").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(modules.router, tags=["modules"])
app.include_router(scenarios.router, tags=["scenarios"])
app.include_router(leaderboard.router, tags=["leaderboard"])


@app.on_event("startup")
def startup():
    create_tables()
    # Eagerly validate all YAML files so bad files surface at boot, not mid-game
    from knowledge import load_all_modules
    loaded = load_all_modules()
    logging.info("Loaded %d module(s): %s", len(loaded), list(loaded.keys()))


@app.get("/health")
def health():
    return {"status": "ok"}
