import Link from "next/link";
import { api } from "@/lib/api";
import { theme } from "@/lib/colors";

export const dynamic = "force-dynamic";

export default async function Home() {
  let modules: Awaited<ReturnType<typeof api.listModules>> = [];
  let error: string | null = null;
  try {
    modules = await api.listModules();
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-1 flex-col px-4 py-10 sm:py-16">
      <header className="mb-10 text-center sm:text-left">
        <div className="inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-1 text-xs font-bold uppercase tracking-wider text-indigo-700 shadow-sm ring-1 ring-indigo-100 dark:bg-zinc-900/70 dark:ring-zinc-800">
          🎮 Volunteer Bootcamp
        </div>
        <h1 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">
          Pick your role.
          <br />
          <span className="bg-gradient-to-r from-indigo-500 via-pink-500 to-amber-500 bg-clip-text text-transparent">
            Play to learn it.
          </span>
        </h1>
        <p className="mt-3 max-w-xl text-base text-zinc-600 dark:text-zinc-400 sm:text-lg">
          Each role has five tiny games. Beat them, beat your best, and you'll
          be shift-ready before the doors open.
        </p>
      </header>

      {error ? (
        <div className="mx-auto max-w-lg rounded-2xl border-2 border-rose-200 bg-rose-50 p-6 text-rose-800">
          <div className="mb-2 font-bold">Couldn't load roles</div>
          <pre className="whitespace-pre-wrap text-xs">{error}</pre>
          <p className="mt-3 text-sm">
            Make sure the FastAPI server is running on{" "}
            <code className="rounded bg-rose-100 px-1">http://localhost:8000</code>{" "}
            (or set <code>NEXT_PUBLIC_API_URL</code>).
          </p>
        </div>
      ) : modules.length === 0 ? (
        <div className="mx-auto max-w-lg rounded-2xl border border-zinc-200 bg-white p-6 text-zinc-700 dark:border-zinc-800 dark:bg-zinc-900 dark:text-zinc-300">
          No volunteer modules found. Drop a YAML file into{" "}
          <code className="rounded bg-zinc-100 px-1 dark:bg-zinc-800">
            backend/data/modules/
          </code>{" "}
          and refresh.
        </div>
      ) : (
        <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {modules.map((m) => {
            const t = theme(m.color);
            return (
              <li key={m.id}>
                <Link
                  href={`/modules/${m.id}`}
                  className={`group block h-full overflow-hidden rounded-3xl border-2 ${t.border} bg-white dark:bg-zinc-900 transition hover:-translate-y-1 hover:shadow-xl`}
                >
                  <div className={`${t.bgGradient} relative h-28 px-5 py-4`}>
                    <div className="absolute -bottom-3 right-4 text-6xl drop-shadow">
                      {m.icon}
                    </div>
                    <div className="text-xs font-bold uppercase tracking-wider text-white/80">
                      Role
                    </div>
                    <div className="mt-1 max-w-[75%] text-xl font-extrabold leading-tight text-white">
                      {m.name}
                    </div>
                  </div>
                  <div className="px-5 py-4">
                    <p className="line-clamp-3 text-sm text-zinc-600 dark:text-zinc-400">
                      {m.description}
                    </p>
                    <div className="mt-4 flex items-center justify-between text-xs text-zinc-500">
                      <span>
                        {m.knowledge_item_count} topics · {m.rule_count} rules
                      </span>
                      <span className={`font-bold ${t.textStrong} group-hover:translate-x-1 transition`}>
                        Play →
                      </span>
                    </div>
                  </div>
                </Link>
              </li>
            );
          })}
        </ul>
      )}

      <footer className="mt-12 text-center text-xs text-zinc-400">
        Built for the hackathon. Knowledge lives in{" "}
        <code>backend/data/modules</code>. Games are generated by Claude on first
        play and cached.
      </footer>
    </main>
  );
}
